for(iter in 1..1525) {
  var topic = "a" // can't possibly match
  switch(topic) {
    "1".part: Fiber.abort("matched 1")
    "2".part: Fiber.abort("matched 2")
    "3".part: Fiber.abort("matched 3")
    "4".part: Fiber.abort("matched 4")
    "5".part: Fiber.abort("matched 5")
    "6".part: Fiber.abort("matched 6")
    "7".part: Fiber.abort("matched 7")
    "8".part: Fiber.abort("matched 8")
    "9".part: Fiber.abort("matched 9")
    "10".part: Fiber.abort("matched 10")
    "11".part: Fiber.abort("matched 11")
    "12".part: Fiber.abort("matched 12")
    "13".part: Fiber.abort("matched 13")
    "14".part: Fiber.abort("matched 14")
    "15".part: Fiber.abort("matched 15")
    "16".part: Fiber.abort("matched 16")
    "17".part: Fiber.abort("matched 17")
    "18".part: Fiber.abort("matched 18")
    "19".part: Fiber.abort("matched 19")
    "20".part: Fiber.abort("matched 20")
    "21".part: Fiber.abort("matched 21")
    "22".part: Fiber.abort("matched 22")
    "23".part: Fiber.abort("matched 23")
    "24".part: Fiber.abort("matched 24")
    "25".part: Fiber.abort("matched 25")
    "26".part: Fiber.abort("matched 26")
    "27".part: Fiber.abort("matched 27")
    "28".part: Fiber.abort("matched 28")
    "29".part: Fiber.abort("matched 29")
    "30".part: Fiber.abort("matched 30")
    "31".part: Fiber.abort("matched 31")
    "32".part: Fiber.abort("matched 32")
    "33".part: Fiber.abort("matched 33")
    "34".part: Fiber.abort("matched 34")
    "35".part: Fiber.abort("matched 35")
    "36".part: Fiber.abort("matched 36")
    "37".part: Fiber.abort("matched 37")
    "38".part: Fiber.abort("matched 38")
    "39".part: Fiber.abort("matched 39")
    "40".part: Fiber.abort("matched 40")
    "41".part: Fiber.abort("matched 41")
    "42".part: Fiber.abort("matched 42")
    "43".part: Fiber.abort("matched 43")
    "44".part: Fiber.abort("matched 44")
    "45".part: Fiber.abort("matched 45")
    "46".part: Fiber.abort("matched 46")
    "47".part: Fiber.abort("matched 47")
    "48".part: Fiber.abort("matched 48")
    "49".part: Fiber.abort("matched 49")
    "50".part: Fiber.abort("matched 50")
  } //switch
} //iter
