for(iter in 1..1525) {
  var topic = "a" // can't possibly match
  switch(topic) {
    "1".part: Fiber.abort("matched 1")
    "2".part: Fiber.abort("matched 2")
    "3".part: Fiber.abort("matched 3")
    "4".part: Fiber.abort("matched 4")
    "5".part: Fiber.abort("matched 5")
    "6".part: Fiber.abort("matched 6")
    "7".part: Fiber.abort("matched 7")
    "8".part: Fiber.abort("matched 8")
    "9".part: Fiber.abort("matched 9")
    "10".part: Fiber.abort("matched 10")
    "11".part: Fiber.abort("matched 11")
    "12".part: Fiber.abort("matched 12")
    "13".part: Fiber.abort("matched 13")
    "14".part: Fiber.abort("matched 14")
    "15".part: Fiber.abort("matched 15")
    "16".part: Fiber.abort("matched 16")
    "17".part: Fiber.abort("matched 17")
    "18".part: Fiber.abort("matched 18")
    "19".part: Fiber.abort("matched 19")
    "20".part: Fiber.abort("matched 20")
    "21".part: Fiber.abort("matched 21")
    "22".part: Fiber.abort("matched 22")
    "23".part: Fiber.abort("matched 23")
    "24".part: Fiber.abort("matched 24")
    "25".part: Fiber.abort("matched 25")
  } //switch
} //iter
